import 'dart:convert';
import 'dart:typed_data';

// ============================================================
// VEIL CODEC — rc4_ksa family (generated by tool/forge)
// ============================================================
// Do NOT hand-edit. Regenerate via `dart run tool/forge/mint.dart`.
// ============================================================

const List<int> _saltBytes = <int>[
  0x2A, 0xC7, 0x07, 0xE7, 0x58, 0x11, 0xA0, 0x4A,
  0xCB, 0x33, 0x81, 0xF6, 0x21, 0x6C, 0xDC, 0x0F,
  0x5B, 0xB2, 0x42, 0xFA,
];

Uint8List _prga(int n) {
  final Uint8List state = Uint8List(256);
  for (int i = 0; i < 256; i++) {
    state[i] = i;
  }
  int j = 0;
  for (int i = 0; i < 256; i++) {
    j = (j + state[i] + _saltBytes[i % _saltBytes.length]) & 0xFF;
    final int tmp = state[i];
    state[i] = state[j];
    state[j] = tmp;
  }
  int a = 0;
  int b = 0;
  final Uint8List out = Uint8List(n);
  for (int k = 0; k < n; k++) {
    a = (a + 1) & 0xFF;
    b = (b + state[a]) & 0xFF;
    final int tmp = state[a];
    state[a] = state[b];
    state[b] = tmp;
    out[k] = state[(state[a] + state[b]) & 0xFF];
  }
  return out;
}

String reveal(List<int> encoded) {
  if (encoded.isEmpty) return '';
  final Uint8List key = _prga(encoded.length);
  final Uint8List out = Uint8List(encoded.length);
  for (int i = 0; i < encoded.length; i++) {
    out[i] = (encoded[i] ^ key[i]) & 0xFF;
  }
  return utf8.decode(out);
}
